# Generated by Django 3.1 on 2021-06-23 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporter', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.AlterField(
            model_name='dailyreview',
            name='pub_date',
            field=models.DateField(),
        ),
    ]
